Fix/charts features
dfid-dvs/client pull request #103
Opened 2021-03-30 09:34 UTC by ShrawanBK

2021-05-03 05:36 UTC, tnagorra approved these changes
Need to fix some minor changes!

2021-05-03 05:36 UTC, tnagorra commented on src/components/ChartModal/ScatterChartConfig/index.tsx
> +    const groupSelector = (item: NumericOption<T>) => item.category;
Need to memoize this

2021-05-03 05:36 UTC, tnagorra commented on src/components/ChartModal/ScatterChartConfig/index.tsx
> +            return defaultData;
Shortcircuit if-else

2021-05-03 05:36 UTC, tnagorra commented on src/components/ChartModal/ScatterChartConfig/index.tsx
> +                    };
Use ternary operators

2021-05-03 05:36 UTC, tnagorra commented on src/components/DendogramTree/index.tsx
> +let NODE_GAP_X = 120;
Why aren't these constants?

2021-05-03 05:36 UTC, tnagorra commented on src/components/DropdownMenu/index.tsx
> +                data-tut={dataTut}
What is `data-tut`?

2021-05-03 05:36 UTC, tnagorra commented on src/components/IndicatorMap/index.tsx
> +    const selectedRegionState: MapStateItem[] | undefined = useMemo(() => {
This is never undefined

2021-05-03 05:36 UTC, tnagorra commented on src/components/IndicatorMap/index.tsx
> +    const hoveredRegionState: MapStateItem[] | undefined = useMemo(() => {
This is never undefined

2021-05-03 05:36 UTC, tnagorra commented on src/components/PolyChart/BiAxialChart/index.tsx
> +    );
No need to memoize this.
We can write this in single expression

2021-05-03 05:36 UTC, tnagorra commented on src/components/PolyChart/ScatterChart/index.tsx
> +    }, [scatterData]);
No need to memoize this.
We can write this in single expression

2021-05-03 05:36 UTC, tnagorra commented on src/components/ProgramSelector/index.tsx
> +    );
Need to memoize this calculation

2021-05-03 05:36 UTC, tnagorra commented on src/components/ProgramSelector/index.tsx
> +        }
We can use `||` to merge both of the if statements

2021-05-03 05:36 UTC, tnagorra commented on src/schema/index.ts
> +/* eslint-disable camelcase */
Any reason why this was changed?

2021-05-03 05:36 UTC, tnagorra commented on src/views/About/TermsAndConditionsPage/LeftTitleItem/index.tsx
> +    }, [id, hash]);
No need to memoize this.
We can write this in single expression

2021-05-03 05:36 UTC, tnagorra commented on src/views/About/TermsAndConditionsPage/TermAndConditionItem/index.tsx
> +    }, [tc.id, hash]);
No need to memoize this.
We can write this in single expression

2021-05-03 05:36 UTC, tnagorra commented on src/views/Dashboard/ProgramDetails/index.tsx
> +    );
Memoize please!

2021-05-03 05:36 UTC, tnagorra commented on src/views/Dashboard/DateRangeSelector/index.tsx
> +        const defYear = [convStartDate, convEndDate];
Why not just read defaultYears?

2021-05-03 05:36 UTC, tnagorra commented on src/views/Dashboard/DateRangeSelector/index.tsx
> +                defYear[0] = new Date(startDate).getFullYear();
Why assign the same value again?

2021-05-03 05:36 UTC, tnagorra commented on src/views/Dashboard/Tooltip/index.tsx
> +                                )?.map(sector => (
We may need to move this outside of the jsx block

2021-05-03 05:36 UTC, tnagorra commented on src/views/RegionProfile/index.tsx
> +    }));
any reason why we are mapping this?

2021-05-03 05:36 UTC, tnagorra commented on src/views/RegionProfile/index.tsx
> +            const totalHiddenIndicators = !!hiddenIndicatorsIds?.length;
It's better to check explicitly for zero and undefined

2021-05-03 05:36 UTC, tnagorra commented on src/views/RegionProfile/index.tsx
> +                                {filteredDendrogramData && filteredDendrogramData.map(res => (
```suggestion
                                {filteredDendrogramData?.map(res => (
```

2021-05-03 05:36 UTC, tnagorra commented on src/views/ProgramProfile/Charts/index.tsx
> +
Let's remove this!

2021-05-03 05:36 UTC, tnagorra commented on src/views/ProgramProfile/Charts/index.tsx
> +        .slice(0, 10);
Let's memoize this

2021-05-03 05:36 UTC, tnagorra commented on src/views/ProgramProfile/Charts/index.tsx
> +            return chartSetting;
Do we even need this!

2021-05-03 05:36 UTC, tnagorra commented on src/views/RegionProfile/NumberOutput/index.tsx
> +            onHideData(id);
We don't need to shortcircuit for this usecase

2021-05-03 05:36 UTC, tnagorra commented on src/views/RegionProfile/Charts/index.tsx
> +            return chartSetting;
Why do this?

2021-05-03 05:37 UTC, tnagorra requested changes
Need to finish minor changes

2021-05-05 03:17 UTC, AdityaKhatri commented on src/Root/styles.css
> +    .rc-slider {
Move rc-slider related classnames to the component where rc slider is used

2021-05-05 03:21 UTC, AdityaKhatri commented on src/components/ChartModal/ScatterChartConfig/index.tsx
> +                }
Move this logic outside to remove one level of nesting.

2021-05-12 08:53 UTC, tnagorra commented on src/components/DendogramTree/index.tsx
> +            onHideDendrogram(treeData.name);
```suggestion
            if (onHideDendrogram) {
                onHideDendrogram(treeData.name);
            }
```

2021-05-12 08:55 UTC, tnagorra commented on src/components/PolyChart/BarChart/index.tsx
> +        [layout],
```suggestion
        [layout, hasLongTiles],
```

2021-05-12 08:58 UTC, tnagorra commented on src/utils/downloadChart.ts
> +        ).then(canvas => canvas.toDataURL('image/png', 1.0));
Why mix usage of then on async await

2021-05-12 09:06 UTC, tnagorra commented on src/views/Dashboard/index.tsx
> +    );
Why use useCallback?

2021-05-12 09:08 UTC, tnagorra commented on src/views/RegionProfile/Indicators/index.tsx
> +        ),
Should not call sort on array as it mutates it. Should create a copy first!

2021-05-12 09:09 UTC, tnagorra commented on src/views/RegionProfile/Indicators/GroupedIndicator/index.tsx
> +            handleHideIndicatorId(category, id);
No need to shortcircuit this

2021-05-12 09:09 UTC, tnagorra commented on src/views/RegionProfile/Indicators/GroupedIndicator/index.tsx
> +            onResetCategory(category);
No need to circuit this

2021-05-12 09:09 UTC, tnagorra commented on src/views/RegionProfile/Indicators/GroupedIndicator/index.tsx
> +            onHideCategory(category);
No need to shortcircuit this

2021-06-03 05:54 UTC, tnagorra commented on src/components/DropdownMenu/index.tsx
> +                data-tut={dataTut}
Shrawan: It's for walkthrough

2021-06-03 07:01 UTC, merged