Fixes/post delivery tasks
dfid-dvs/client pull request #114
Opened 2021-06-10 09:50 UTC by ShrawanBK

2021-06-14 05:00 UTC, AdityaKhatri requested changes

2021-06-14 05:00 UTC, AdityaKhatri commented on src/components/ChartModal/BarChartConfig/index.tsx
> +        acronymSelector: primaryAcronymSelector,
```suggestion
        acronymSelector,
```

2021-06-14 05:00 UTC, AdityaKhatri commented on src/components/ChartModal/BarChartConfig/index.tsx
> +                acronymSelector: primaryAcronymSelector,
```suggestion
                acronymSelector,
```

2021-06-14 05:00 UTC, AdityaKhatri commented on src/components/ChartModal/BarChartConfig/index.tsx
> +            order, autoOrderField, primaryKeySelector, primaryAcronymSelector,
```suggestion
            order, autoOrderField, primaryKeySelector, acronymSelector,
```

2021-06-14 05:00 UTC, AdityaKhatri commented on src/views/Dashboard/RegionDetails/Charts/index.tsx
> +        dependencies: [504],
Lets define the ids as enums and use it here.

2021-06-14 05:00 UTC, AdityaKhatri commented on src/views/Dashboard/RegionDetails/Charts/index.tsx
> +            valueSelector: item => item.indicators[156] || null,
Lets define the ids as enums and use it here.

2021-06-14 05:00 UTC, AdityaKhatri commented on src/views/Dashboard/RegionDetails/Charts/index.tsx
> +                valueSelector: item => item.indicators[156] || null,
Lets define the ids as enums and use it here.

2021-06-14 05:00 UTC, AdityaKhatri commented on src/views/Dashboard/RegionDetails/Charts/index.tsx
> +        dependencies: [156],
Lets define the ids as enums and use it here.

2021-06-14 05:00 UTC, AdityaKhatri commented on src/views/Dashboard/RegionDetails/Charts/index.tsx
> +            valueSelector: item => item.indicators[504] || null,
Lets define the ids as enums and use it here.

2021-06-14 05:00 UTC, AdityaKhatri commented on src/components/PolyChart/BarChart/index.tsx
> +    if (!payload || payload.length <= 0) { return null; }
```suggestion
    if (!payload || payload.length <= 0) {
        return null;
    }
```

2021-06-15 04:19 UTC, tnagorra requested changes

2021-06-15 04:19 UTC, tnagorra commented on src/components/PolyChart/BarChart/index.tsx
> +    if (administrationIndex <= 0) return words.join(' ');
Always add block for if/else blocks

2021-06-15 04:19 UTC, tnagorra commented on src/components/PolyChart/BarChart/index.tsx
> +    if (active) {
It's easier to shortcircuit

2021-06-15 04:19 UTC, tnagorra commented on src/components/PolyChart/BiAxialChart/index.tsx
> +    if (administrationIndex <= 0) return words.join(' ');
Always add if/else block (body with curly braces)

2021-06-15 04:19 UTC, tnagorra commented on src/components/PolyChart/BiAxialChart/index.tsx
> +        i => caseInsensitiveSubmatch(i, 'Province') || caseInsensitiveSubmatch(i, 'District') || caseInsensitiveSubmatch(i, 'Municipality'),
Why not use regex?

2021-06-15 04:19 UTC, tnagorra commented on src/components/PolyChart/BiAxialChart/index.tsx
> +    if (active) {
It's better to shortcircuit

2021-06-29 03:52 UTC, AdityaKhatri approved these changes

2021-06-29 15:47 UTC, merged